### ISSUE TITLE
schema_salad.exceptions.ValidationException tried...

### ISSUE THREAD

**Issue by jjkoehorst** [ResearchObject/runcrate#39]
Not exactly sure what is happening here and sorry for the larger prov size but otherwise it takes a long time to compute on my laptop so I had to include the indexed lookup database.

http://download.systemsbiology.nl/unlock/cwl/issues/PROV_ngtax.zip

```
Traceback (most recent call last):
  File "/Users/jasperk/mambaforge/bin/runcrate", line 8, in <module>
    sys.exit(cli())
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/runcrate/cli.py", line 67, in convert
    builder = ProvCrateBuilder(root, workflow_name, license, readme)
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/runcrate/convert.py", line 187, in __init__
    self.cwl_defs = get_workflow(self.wf_path)
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/runcrate/convert.py", line 167, in get_workflow
    defs = load_document_by_yaml(json_wf, wf_path.absolute().as_uri())
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/cwl_utils/parser/__init__.py", line 128, in load_document_by_yaml
    result = cwl_v1_2.load_document_by_yaml(
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/cwl_utils/parser/cwl_v1_2.py", line 15471, in load_document_by_yaml
    return _document_load(
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/cwl_utils/parser/cwl_v1_2.py", line 578, in _document_load
    return loader.load(doc["$graph"], baseuri, loadingOptions)
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/cwl_utils/parser/cwl_v1_2.py", line 417, in load
    raise ValidationException("", None, errors, "-")
schema_salad.exceptions.ValidationException: - tried _RecordLoader but
  Expected a dict
- tried _RecordLoader but
  Expected a dict
- tried _RecordLoader but
  Expected a dict
- tried _RecordLoader but
  Expected a dict
- tried _ArrayLoader but
  - tried _ArrayLoader but
    Expected a list
  - tried _UnionLoader but
    - tried _RecordLoader but
      Trying 'CommandLineTool'
        the `outputs` field is not valid because:
          - tried _ArrayLoader but
            - tried _ArrayLoader but
              Expected a list
            - tried _RecordLoader but
              Trying 'CommandOutputParameter'
PROV_ngtax/workflow/packed.cwl#ngtax.cwl/reference_db_lookup:3:9:                       the `type`
                                                                                     field is not valid because:
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('File', 'Directory')
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('stdout',)
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('stderr',)
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _PrimitiveLoader but
                                                                                         Expected a
                                                                                         tuple but got NoneType
                                                                                       - tried
                                                                                       _ArrayLoader but
                                                                                         Expected a
                                                                                         list
PROV_ngtax/workflow/packed.cwl#ngtax.cwl/reference_db_lookup:4:13:                     invalid field
                                                                                     `class`, expected one of:
                                                                                     `label`, `secondaryFiles`,
                                                                                     `streamable`, `doc`, `id`,
                                                                                     `format`, `type`,
                                                                                     `outputBinding`
            - tried _ArrayLoader but
              Expected a list
            - tried _RecordLoader but
              Trying 'CommandOutputParameter'
PROV_ngtax/workflow/packed.cwl#ngtax.cwl/reference_db_lookup:79:9:                     the `type`
                                                                                     field is not valid because:
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('File', 'Directory')
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('stdout',)
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('stderr',)
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _PrimitiveLoader but
                                                                                         Expected a
                                                                                         tuple but got NoneType
                                                                                       - tried
                                                                                       _ArrayLoader but
                                                                                         Expected a
                                                                                         list
PROV_ngtax/workflow/packed.cwl#ngtax.cwl/reference_db_lookup:80:13:                   invalid field
                                                                                     `class`, expected one of:
                                                                                     `label`, `secondaryFiles`,
                                                                                     `streamable`, `doc`, `id`,
                                                                                     `format`, `type`,
                                                                                     `outputBinding`
            - tried _ArrayLoader but
              Expected a list
            - tried _RecordLoader but
              Trying 'CommandOutputParameter'
PROV_ngtax/workflow/packed.cwl#ngtax.cwl/reference_db_lookup:216:9:                   the `type`
                                                                                     field is not valid because:
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('File', 'Directory')
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('stdout',)
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('stderr',)
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _PrimitiveLoader but
                                                                                         Expected a
                                                                                         tuple but got NoneType
                                                                                       - tried
                                                                                       _ArrayLoader but
                                                                                         Expected a
                                                                                         list
PROV_ngtax/workflow/packed.cwl#ngtax.cwl/reference_db_lookup:217:13:                 invalid field
                                                                                     `class`, expected one of:
                                                                                     `label`, `secondaryFiles`,
                                                                                     `streamable`, `doc`, `id`,
                                                                                     `format`, `type`,
                                                                                     `outputBinding`
            - tried _ArrayLoader but
              Expected a list
            - tried _RecordLoader but
              Trying 'CommandOutputParameter'
PROV_ngtax/workflow/packed.cwl#ngtax.cwl/reference_db_lookup:448:9:                   the `type`
                                                                                     field is not valid because:
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('File', 'Directory')
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('stdout',)
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('stderr',)
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _PrimitiveLoader but
                                                                                         Expected a
                                                                                         tuple but got NoneType
                                                                                       - tried
                                                                                       _ArrayLoader but
                                                                                         Expected a
                                                                                         list
PROV_ngtax/workflow/packed.cwl#ngtax.cwl/reference_db_lookup:449:13:                 invalid field
                                                                                     `class`, expected one of:
                                                                                     `label`, `secondaryFiles`,
                                                                                     `streamable`, `doc`, `id`,
                                                                                     `format`, `type`,
                                                                                     `outputBinding`
            - tried _ArrayLoader but
              Expected a list
            - tried _RecordLoader but
              Trying 'CommandOutputParameter'
PROV_ngtax/workflow/packed.cwl#ngtax.cwl/reference_db_lookup:574:9:                   the `type`
                                                                                     field is not valid because:
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('File', 'Directory')
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('stdout',)
                                                                                       - tried
                                                                                       _EnumLoader but
                                                                                         Expected
                                                                                         one of ('stderr',)
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _RecordLoader but
                                                                                         Expected a
                                                                                         dict
                                                                                       - tried
                                                                                       _PrimitiveLoader but
                                                                                         Expected a
                                                                                         tuple but got NoneType
                                                                                       - tried
                                                                                       _ArrayLoader but
                                                                                         Expected a
                                                                                         list
PROV_ngtax/workflow/packed.cwl#ngtax.cwl/reference_db_lookup:575:13:                 invalid field
                                                                                     `class`, expected one of:
                                                                                     `label`, `secondaryFiles`,
                                                                                     `streamable`, `doc`, `id`,
                                                                                     `format`, `type`,
                                                                                     `outputBinding`
          - tried _RecordLoader but
            Expected a dict
    - tried _RecordLoader but
      Not a ExpressionTool
    - tried _RecordLoader but
      Not a Workflow
    - tried _RecordLoader but
      Not a Operation
```

**Comment by jjkoehorst** [comment]
This might actually be a cwl_utils issue and not a runcrate...
