### ISSUE TITLE
AttributeError: 'CommandLineTool' object has no attribute 'rsplit'

### ISSUE THREAD

**Issue by jjkoehorst** [ResearchObject/runcrate#49]
Was testing some provenance workflows in CWLTool and encountered the following:

`runcrate convert -o bla provenance`

```
Traceback (most recent call last):
  File "/Users/jasperk/mambaforge/bin/runcrate", line 8, in <module>
    sys.exit(cli())
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jasperk/mambaforge/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jasperk/gitlab/runcrate/src/runcrate/cli.py", line 67, in convert
    builder = ProvCrateBuilder(root, workflow_name, license, readme)
  File "/Users/jasperk/gitlab/runcrate/src/runcrate/convert.py", line 184, in __init__
    self.step_maps = self._get_step_maps(self.cwl_defs)
  File "/Users/jasperk/gitlab/runcrate/src/runcrate/convert.py", line 208, in _get_step_maps
    rval[k][f] = {"tool": get_fragment(s.run), "pos": pos_map[f]}
  File "/Users/jasperk/gitlab/runcrate/src/runcrate/convert.py", line 112, in get_fragment
    return uri.rsplit("#", 1)[-1]
AttributeError: 'CommandLineTool' object has no attribute 'rsplit'
```

The zip: http://download.systemsbiology.nl/unlock/cwl/issues/cwl_test_no_listing.zip

**Comment by mr-c** [comment]
Ah, this is an inline Process specified in the `run` section. Instead of a reference to another document
